///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckAndUncheckFunctionalityOfEditDashboard recording.
    /// </summary>
    [TestModule("53868274-cab7-46f7-9867-5a78b6054c75", ModuleType.Recording, 1)]
    public partial class CheckAndUncheckFunctionalityOfEditDashboard : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest1Repository repository.
        /// </summary>
        public static MyTest1Repository repo = MyTest1Repository.Instance;

        static CheckAndUncheckFunctionalityOfEditDashboard instance = new CheckAndUncheckFunctionalityOfEditDashboard();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckAndUncheckFunctionalityOfEditDashboard()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckAndUncheckFunctionalityOfEditDashboard Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.AccountSettingBtn' at Center", repo.ComPentairPentairhome.AccountSettingBtnInfo, new RecordItemIndex(0));
            repo.ComPentairPentairhome.AccountSettingBtn.Touch();
            Delay.Milliseconds(300);
            
            try {
                Report.Log(ReportLevel.Info, "Wait", "(Optional Action)\r\nWaiting 5s to exist. Associated repository item: 'ComPentairPentairhome.EditDashboardTileOnAccSetting'", repo.ComPentairPentairhome.EditDashboardTileOnAccSettingInfo, new ActionTimeout(5000), new RecordItemIndex(1));
                repo.ComPentairPentairhome.EditDashboardTileOnAccSettingInfo.WaitForExists(5000);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.EditDashboardTileOnAccSetting' at Center", repo.ComPentairPentairhome.EditDashboardTileOnAccSettingInfo, new RecordItemIndex(2));
            repo.ComPentairPentairhome.EditDashboardTileOnAccSetting.Touch();
            Delay.Milliseconds(300);
            
            try {
                Report.Log(ReportLevel.Info, "Delay", "(Optional Action)\r\nWaiting for 2s.", new RecordItemIndex(3));
                Delay.Duration(2000, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            try {
                Report.Screenshot(ReportLevel.Info, "User", "EditDashboardScreen", repo.ComPentairPentairhome.EditDashboardScreen, false, new RecordItemIndex(4));
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            try {
                Report.Log(ReportLevel.Info, "Touch", "(Optional Action)\r\nTouch item 'ComPentairPentairhome.EScImageOnEditDashboard' at Center", repo.ComPentairPentairhome.EScImageOnEditDashboardInfo, new RecordItemIndex(5));
                repo.ComPentairPentairhome.EScImageOnEditDashboard.Touch();
                Delay.Milliseconds(300);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            try {
                Report.Log(ReportLevel.Info, "Delay", "(Optional Action)\r\nWaiting for 3s.", new RecordItemIndex(6));
                Delay.Duration(3000, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.SaveonEditDashboard' at Center", repo.ComPentairPentairhome.SaveonEditDashboardInfo, new RecordItemIndex(7));
            repo.ComPentairPentairhome.SaveonEditDashboard.Touch();
            Delay.Milliseconds(300);
            
            try {
                Report.Log(ReportLevel.Info, "Wait", "(Optional Action)\r\nWaiting 5s to not exist. Associated repository item: 'ComPentairPentairhome.AccountSettingBtn'", repo.ComPentairPentairhome.AccountSettingBtnInfo, new ActionTimeout(5000), new RecordItemIndex(8));
                repo.ComPentairPentairhome.AccountSettingBtnInfo.WaitForNotExists(5000);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(8)); }
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.AccountSettingBtn' at Center", repo.ComPentairPentairhome.AccountSettingBtnInfo, new RecordItemIndex(9));
            repo.ComPentairPentairhome.AccountSettingBtn.Touch();
            Delay.Milliseconds(300);
            
            try {
                //Report.Log(ReportLevel.Info, "Wait", "(Optional Action)\r\nWaiting 5s for the attribute 'AccessibilityLabel' to equal the specified value 'Edit Dashboard'. Associated repository item: 'ComPentairPentairhome.EditDashboardTileOnAccSetting'", repo.ComPentairPentairhome.EditDashboardTileOnAccSettingInfo, new RecordItemIndex(10));
                //repo.ComPentairPentairhome.EditDashboardTileOnAccSettingInfo.WaitForAttributeEqual(5000, "AccessibilityLabel", "Edit Dashboard");
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(10)); }
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.EditDashboardTileOnAccSetting' at Center", repo.ComPentairPentairhome.EditDashboardTileOnAccSettingInfo, new RecordItemIndex(11));
            repo.ComPentairPentairhome.EditDashboardTileOnAccSetting.Touch();
            Delay.Milliseconds(300);
            
            try {
                Report.Log(ReportLevel.Info, "Delay", "(Optional Action)\r\nWaiting for 5s.", new RecordItemIndex(12));
                Delay.Duration(5000, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(12)); }
            
            try {
                Report.Screenshot(ReportLevel.Info, "User", "EditDashboardScreen", repo.ComPentairPentairhome.EditDashboardScreen, false, new RecordItemIndex(13));
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(13)); }
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.EScImageOnEditDashboard' at Center", repo.ComPentairPentairhome.EScImageOnEditDashboardInfo, new RecordItemIndex(14));
            repo.ComPentairPentairhome.EScImageOnEditDashboard.Touch();
            Delay.Milliseconds(300);
            
            try {
                Report.Log(ReportLevel.Info, "Delay", "(Optional Action)\r\nWaiting for 3s.", new RecordItemIndex(15));
                Delay.Duration(3000, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(15)); }
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.SaveonEditDashboard' at Center", repo.ComPentairPentairhome.SaveonEditDashboardInfo, new RecordItemIndex(16));
            repo.ComPentairPentairhome.SaveonEditDashboard.Touch();
            Delay.Milliseconds(300);
            
            try {
                Report.Log(ReportLevel.Info, "Delay", "(Optional Action)\r\nWaiting for 3s.", new RecordItemIndex(17));
                Delay.Duration(3000, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(17)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
