///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RemoveESC recording.
    /// </summary>
    [TestModule("db14c7b2-b0cb-4750-ad89-6242b7a26e80", ModuleType.Recording, 1)]
    public partial class RemoveESC : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest1Repository repository.
        /// </summary>
        public static MyTest1Repository repo = MyTest1Repository.Instance;

        static RemoveESC instance = new RemoveESC();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RemoveESC()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RemoveESC Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Wait", "(Optional Action)\r\nWaiting 5s for the attribute 'AccessibilityId' to equal the specified value 'deviceImage'. Associated repository item: 'ComPentairPentairhome.DeviceImage'", repo.ComPentairPentairhome.DeviceImageInfo, new RecordItemIndex(0));
                repo.ComPentairPentairhome.DeviceImageInfo.WaitForAttributeEqual(5000, "AccessibilityId", "deviceImage");
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.DeviceImage' at Center", repo.ComPentairPentairhome.DeviceImageInfo, new RecordItemIndex(1));
            repo.ComPentairPentairhome.DeviceImage.Touch();
            Delay.Milliseconds(300);
            
            try {
                Report.Log(ReportLevel.Info, "Wait", "(Optional Action)\r\nWaiting 5s for the attribute 'AccessibilityId' to equal the specified value 'headerRightImage'. Associated repository item: 'ComPentairPentairhome.ESCSetting'", repo.ComPentairPentairhome.ESCSettingInfo, new RecordItemIndex(2));
                repo.ComPentairPentairhome.ESCSettingInfo.WaitForAttributeEqual(5000, "AccessibilityId", "headerRightImage");
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.ESCSetting' at Center", repo.ComPentairPentairhome.ESCSettingInfo, new RecordItemIndex(3));
            repo.ComPentairPentairhome.ESCSetting.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(4));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.RemoveDevice' at Center", repo.ComPentairPentairhome.RemoveDeviceInfo, new RecordItemIndex(5));
            repo.ComPentairPentairhome.RemoveDevice.Touch();
            Delay.Milliseconds(300);
            
            try {
                Report.Log(ReportLevel.Info, "Delay", "(Optional Action)\r\nWaiting for 3s.", new RecordItemIndex(6));
                Delay.Duration(3000, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
            try {
                Report.Screenshot(ReportLevel.Info, "User", "RemoveDevice", repo.ComPentairPentairhome.RemoveDeviceAreYouSureYouWantToR, false, new RecordItemIndex(7));
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (AccessibilityLabel='Are you sure you want to remove intellisync from your account? All settings will be restored to their factory defaults and all data will be deleted.') on item 'ComPentairPentairhome.AreYouSureYouWantToRemoveIntellis'.", repo.ComPentairPentairhome.AreYouSureYouWantToRemoveIntellisInfo, new RecordItemIndex(8));
                Validate.AttributeEqual(repo.ComPentairPentairhome.AreYouSureYouWantToRemoveIntellisInfo, "AccessibilityLabel", "Are you sure you want to remove intellisync from your account? All settings will be restored to their factory defaults and all data will be deleted.", null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(8)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (AccessibilityLabel='REMOVE') on item 'ComPentairPentairhome.REMOVE1'.", repo.ComPentairPentairhome.REMOVE1Info, new RecordItemIndex(9));
                Validate.AttributeEqual(repo.ComPentairPentairhome.REMOVE1Info, "AccessibilityLabel", "REMOVE", null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(9)); }
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(10));
            Delay.Duration(2000, false);
            
            try {
                Report.Log(ReportLevel.Info, "Touch", "(Optional Action)\r\nTouch item 'ComPentairPentairhome.REMOVE1' at Center", repo.ComPentairPentairhome.REMOVE1Info, new RecordItemIndex(11));
                repo.ComPentairPentairhome.REMOVE1.Touch();
                Delay.Milliseconds(300);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(11)); }
            
            try {
                Report.Log(ReportLevel.Info, "Delay", "(Optional Action)\r\nWaiting for 5s.", new RecordItemIndex(12));
                Delay.Duration(5000, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(12)); }
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.HomeIcon' at Center", repo.ComPentairPentairhome.HomeIconInfo, new RecordItemIndex(13));
            repo.ComPentairPentairhome.HomeIcon.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(14));
            Delay.Duration(5000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
