///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SensorGraphs recording.
    /// </summary>
    [TestModule("25355dfd-3957-4b10-aa0b-e8fbe5a730e3", ModuleType.Recording, 1)]
    public partial class SensorGraphs : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest1Repository repository.
        /// </summary>
        public static MyTest1Repository repo = MyTest1Repository.Instance;

        static SensorGraphs instance = new SensorGraphs();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SensorGraphs()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SensorGraphs Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.WaterTemp' at Center", repo.ComPentairPentairhome.WaterTempInfo, new RecordItemIndex(0));
            repo.ComPentairPentairhome.WaterTemp.Touch();
            Delay.Milliseconds(300);
            
            try {
                Report.Log(ReportLevel.Info, "Wait", "(Optional Action)\r\nWaiting 5s for the attribute 'AccessibilityLabel' to equal the specified value 'Water Temp'. Associated repository item: 'ComPentairPentairhome.WaterTempTileonSenorDash'", repo.ComPentairPentairhome.WaterTempTileonSenorDashInfo, new RecordItemIndex(1));
                repo.ComPentairPentairhome.WaterTempTileonSenorDashInfo.WaitForAttributeEqual(5000, "AccessibilityLabel", "Water Temp");
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.WaterTempTileonSenorDash' at Center", repo.ComPentairPentairhome.WaterTempTileonSenorDashInfo, new RecordItemIndex(2));
            repo.ComPentairPentairhome.WaterTempTileonSenorDash.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.Hourly' at Center", repo.ComPentairPentairhome.HourlyInfo, new RecordItemIndex(3));
            repo.ComPentairPentairhome.Hourly.Touch();
            Delay.Milliseconds(300);
            
            try {
                Report.Log(ReportLevel.Info, "Delay", "(Optional Action)\r\nWaiting for 3s.", new RecordItemIndex(4));
                Delay.Duration(3000, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            try {
                Report.Screenshot(ReportLevel.Info, "User", "HourlyWaterGraph", repo.ComPentairPentairhome.WaterTemperatureHistoryHourlyDailyW, false, new RecordItemIndex(5));
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            try {
                Report.Log(ReportLevel.Info, "Wait", "(Optional Action)\r\nWaiting 5s for the attribute 'AccessibilityLabel' to equal the specified value 'Daily'. Associated repository item: 'ComPentairPentairhome.DailyWaterTempGraph'", repo.ComPentairPentairhome.DailyWaterTempGraphInfo, new RecordItemIndex(6));
                repo.ComPentairPentairhome.DailyWaterTempGraphInfo.WaitForAttributeEqual(5000, "AccessibilityLabel", "Daily");
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.DailyWaterTempGraph' at Center", repo.ComPentairPentairhome.DailyWaterTempGraphInfo, new RecordItemIndex(7));
            repo.ComPentairPentairhome.DailyWaterTempGraph.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(8));
            Delay.Duration(5000, false);
            
            try {
                Report.Screenshot(ReportLevel.Info, "User", "DailyWaterTempgraph", repo.ComPentairPentairhome.WaterTemperatureHistoryHourlyDailyW1, false, new RecordItemIndex(9));
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(9)); }
            
            try {
                Report.Log(ReportLevel.Info, "Wait", "(Optional Action)\r\nWaiting 5s to not exist. Associated repository item: 'ComPentairPentairhome.WeeklyWaterTempgraph'", repo.ComPentairPentairhome.WeeklyWaterTempgraphInfo, new ActionTimeout(5000), new RecordItemIndex(10));
                repo.ComPentairPentairhome.WeeklyWaterTempgraphInfo.WaitForNotExists(5000);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(10)); }
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.WeeklyWaterTempgraph' at Center", repo.ComPentairPentairhome.WeeklyWaterTempgraphInfo, new RecordItemIndex(11));
            repo.ComPentairPentairhome.WeeklyWaterTempgraph.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 6s.", new RecordItemIndex(12));
            Delay.Duration(6000, false);
            
            try {
                Report.Screenshot(ReportLevel.Info, "User", "WeeklyWaterTempGraph", repo.ComPentairPentairhome.WaterTemperatureHistoryHourlyDailyW2, false, new RecordItemIndex(13));
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(13)); }
            
            try {
                Report.Log(ReportLevel.Info, "Wait", "(Optional Action)\r\nWaiting 5s to not exist. Associated repository item: 'ComPentairPentairhome.MonthlyWaterTempGraph'", repo.ComPentairPentairhome.MonthlyWaterTempGraphInfo, new ActionTimeout(5000), new RecordItemIndex(14));
                repo.ComPentairPentairhome.MonthlyWaterTempGraphInfo.WaitForNotExists(5000);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(14)); }
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.MonthlyWaterTempGraph' at Center", repo.ComPentairPentairhome.MonthlyWaterTempGraphInfo, new RecordItemIndex(15));
            repo.ComPentairPentairhome.MonthlyWaterTempGraph.Touch();
            Delay.Milliseconds(300);
            
            try {
                Report.Log(ReportLevel.Info, "Delay", "(Optional Action)\r\nWaiting for 5s.", new RecordItemIndex(16));
                Delay.Duration(5000, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(16)); }
            
            try {
                Report.Screenshot(ReportLevel.Info, "User", "MonthlyWaterTempGraph", repo.ComPentairPentairhome.WaterTemperatureHistoryHourlyDailyW1, false, new RecordItemIndex(17));
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(17)); }
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPentairPentairhome.HomeIcon' at Center", repo.ComPentairPentairhome.HomeIconInfo, new RecordItemIndex(18));
            repo.ComPentairPentairhome.HomeIcon.Touch();
            Delay.Milliseconds(300);
            
            try {
                Report.Log(ReportLevel.Info, "Delay", "(Optional Action)\r\nWaiting for 3s.", new RecordItemIndex(19));
                Delay.Duration(3000, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(19)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
